routes/web.php
<?php

use App\Http\Controllers as Controller;
use App\Providers\RouteServiceProvider;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::redirect('/', RouteServiceProvider::HOME);

Route::get('/home', [Controller\HomeController::class, 'index'])->name('home');

Route::resource('todos', Controller\ToDoController::class,)->except('create', 'index', 'show');

app/Models/ToDo.php
<?php declare(strict_types=1);

namespace App\Models;

use Illuminate\Database\Eloquent\Collection;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations as Relationship;

/**
 * @property Collection $tagged
 * @property User $user
 */
final class ToDo extends Model
{
    use HasFactory;

    protected $dates = [
        'due_date',
    ];

    protected $fillable = [
        'user_id',
        'contents',
        'due_date',
    ];

    protected $table = 'todos';

    public function tagged(): Relationship\BelongsToMany
    {
        return $this->belongsToMany(User::class, 'todos_users', 'todo_id');
    }

    public function user(): Relationship\BelongsTo
    {
        return $this->belongsTo(User::class);
    }
}

app/Models/User.php
<?php declare(strict_types=1);

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Relations as Relationship;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

/**
 * @property Collection $tagged
 * @property Collection $todos
 */
final class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function tagged(): Relationship\BelongsToMany
    {
        return $this->belongsToMany(ToDo::class, 'todos_users', relatedPivotKey: 'todo_id');
    }

    public function todos(): Relationship\HasMany
    {
        return $this->hasMany(ToDo::class);
    }
}

app/Http/Controllers/Controller.php
<?php declare(strict_types=1);

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

abstract class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home')->with('todos', Auth::user()->todos);
    }
}

app/Http/Controllers/ToDoController.php
<?php declare(strict_types=1);

namespace App\Http\Controllers;

use App\Http\Requests\ToDoRequest;
use App\Models\ToDo;
use App\Models\User;
use App\Providers\RouteServiceProvider;
use Illuminate\Auth\Access\AuthorizationException;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\Auth;

final class ToDoController extends Controller
{
    /**
     * Store a newly created resource in storage.
     *
     * @param ToDoRequest $request
     * @return RedirectResponse
     */
    public function store(ToDoRequest $request)
    {
        /** @var ToDo $todo */
        $todo = Auth::user()->todos()->create($request->only('contents', 'due_date'));
        $todo->tagged()->sync($request->get('tagged'));
        return back()->with('status', 'Todo added!');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param ToDo $todo
     * @return Response
     */
    public function edit(ToDo $todo)
    {
        return response()->view('todo.edit', ['todo' => $todo]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param ToDoRequest $request
     * @param ToDo $todo
     * @return RedirectResponse
     */
    public function update(ToDoRequest $request, ToDo $todo)
    {
        static::verifyOwnership($todo, $request->user());
        $todo->update($request->only('contents', 'due_date'));
        $todo->tagged()->sync($request->get('tagged'));
        return response()->redirectTo(RouteServiceProvider::HOME)->with('status', 'Todo updated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param ToDo $todo
     * @return RedirectResponse
     * @throws AuthorizationException
     */
    public function destroy(ToDo $todo)
    {
        self::verifyOwnership($todo, Auth::user());
        $todo->deleteOrFail();
        return back()->with('status', 'Item deleted!');
    }

    /**
     * @throws AuthorizationException
     */
    private static function verifyOwnership(ToDo $todo, User $owner): void
    {
        if ($todo->user()->isNot($owner)) {
            throw new AuthorizationException('You are not allowed to perform these actions on other users items.');
        }
    }
}

resources/views/home.blade.php
@php
    use App\Models\ToDo;
    use Illuminate\Database\Eloquent\Collection;
    /** @var Collection<ToDo> $todos */
@endphp

@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    <ul class="list-group">
                        @foreach($todos as $todo)
                        <li class="list-group-item">
                            <a class="btn btn-info" href="{{ route('todos.edit', $todo) }}">Update</a>
                            <a class="btn btn-danger" onclick="destroyTodo({{ $todo->getKey() }})">Delete</a>
                            |
                            {{ $todo->getAttribute('contents') }} @if($todo->getAttribute('due_date')) - Due in {{ now()->diffForHumans($todo->getAttribute('due_date'), \Carbon\CarbonInterface::DIFF_ABSOLUTE) }} @endif
                            @if ($todo->tagged->isNotEmpty()) | ({{ $todo->tagged->pluck('name')->implode(', ') }})@endif
                        </li>
                        @endforeach
                        <li class="list-group-item">
                            <form method="post" action="{{ route('todos.store') }}">
                                @csrf
                                <input type="text" class="form-control" name="contents" placeholder="My New Todo!">
                                <input type="date" class="form-control" name="due_date" min="{{ now()->format('Y-m-d') }}" placeholder="Due Date">
                                <select name="tagged[]" multiple class="custom-select">
                                    @foreach(\App\Models\User::all(['id', 'name']) as $user)
                                        <option value="{{ $user->getKey() }}">{{ $user->getAttribute('name') }}</option>
                                    @endforeach
                                </select>
                                <input type="submit" class="btn btn-primary btn-block" value="Make it so!">
                            </form>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>

<form id="destroy-form" method="POST" class="d-none">
    @csrf
    <input type="hidden" name="_method" value="DELETE">
</form>

<script>
    function destroyTodo(action) {
        let form = document.getElementById('destroy-form');
        form.setAttribute('action', 'todos/' + action);
        form.submit();
    }
</script>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            @if (Route::has('login'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                                </li>
                            @endif

                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }}
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/todo/edit.blade.php
@php
    use App\Models\ToDo;
    /** @var ToDo $todo */
@endphp

@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">Editing Todo</div>

                    <div class="card-body">
                        <form action="{{ route('todos.update', $todo) }}" method="post">
                            @csrf
                            @method('patch')
                            <input type="text" class="form-control" name="contents" value="{{ $todo->getAttribute('contents') }}">
                            <input type="date" class="form-control" name="due date" value="{{ $todo->getAttribute('due_date')?->format('Y-m-d') }}">
                            <select name="tagged[]" multiple class="custom-select">
                                @foreach(\App\Models\User::all(['id', 'name']) as $user)
                                <option
                                    value="{{ $user->getKey() }}"
                                    @if($todo->tagged->pluck('id')->contains($user->getKey())) selected @endif
                                >
                                    {{ $user->getAttribute('name') }}
                                </option>
                                @endforeach
                            </select>
                            <input type="submit" class="form-control btn btn-primary" value="Make it so!">
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection